# Введите токен сообщества (бота)
vk_token: "token"

# Введите список пользователей которые могут пользоватся ботом (их цифровые ID)
# Узнать свой цифровой ID можно в настройках профиля
users:
  - 12345678
  - 87654321

group:
  # Разрешено ли взаимодействовать с ботом в беседе?
  enable: True

  # Какой символ надо ввести в начало команды чтобы выполнить команду
  symbol: "!"

# Список команд которые будут запрещены
blocked:
  - "stop"
  - "whitelist"



# Введите IP адрес сервера
# Сойдет как домен, так и обычный цифровой IP
address: "ruby.MCPEhost.ru"

# Введите ПОРТ сервера
port: 23038

# Введите RCON пароль сервера
password: "qwerty1"
